identity:
    orgId: j4fntv
    typeId: Cambien
    deviceId: cambien001
auth:
    token: 12345678
options:
    domain: internetofthings.ibmcloud.com
    logLevel: debug
    mqtt:
        port: 8883
        transport: tcp
        cleanStart: true
        sessionExpiry: 7200
        keepAlive: 120
        # caFile: /path/to/certificateAuthorityFile.pem