myConfig = { 
    "identity": {
        "orgId": "org1id",
        "typeId": "raspberry-pi-3"
        "deviceId": "00ef08ac05"
    }.
    "auth" {
        "token": "Ab$76s)asj8_s5"
    },
    # "options": {
    #     "domain": "internetofthings.ibmcloud.com",
    #     "logLevel": "error|warning|info|debug",
    #     "mqtt": {
    #         "port": 8883,
    #         "transport": "tcp|websockets",
    #         "cleanStart": True|False,
    #         "sessionExpiry": 3600,
    #         "keepAlive": 60,
    #         "caFile": "/path/to/certificateAuthorityFile.pem"
    #     }
    # }
}
client = wiotp.sdk.device.DeviceClient(config=myConfig, logHandlers=None)